# Use the official image as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

# Use SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# Copy csproj and restore
COPY ["CarInfo.csproj", "./"]
RUN dotnet restore "CarInfo.csproj"

# Copy everything else and build
COPY . .
RUN dotnet build "CarInfo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CarInfo.csproj" -c Release -o /app/publish

# Copy build app to base image and define entry point
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CarInfo.dll"]
